config/routes.rb
TumblrClone::Application.routes.draw do
  root to: redirect('/dashboard')
  
  get 'password-reset-new', to: 'sessions#password_reset_new', as: 'password_reset_new'
  post 'password-reset-send', to: 'sessions#password_reset_send', as: 'password_reset_send'
  get 'password-reset-edit/:id', to: 'sessions#password_reset_edit', as: 'password_reset_edit'
  post 'password_reset_update/:id', to: 'sessions#password_reset_update', as: 'password_reset_update'
  get 'login', to: 'sessions#new', as: 'login'
  post 'signin', to: 'sessions#create', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  match '/auth/facebook/callback', to: 'sessions#facebook_signin'
  match '/auth/failure', to: 'sessions#new'
  get 'facebook-destroy', to: 'sessions#facebook_destroy', as: 'facebook_destroy'
  
  resources :users, only: [:new, :create, :show, :update, :destroy]
  get 'dashboard', to: 'users#show', as: 'home'
  get 'findblogs', to: 'users#findblogs', as: 'findblogs'
  get 'settings', to: 'users#edit', as: 'settings'
  get 'users/:id/public', to: 'users#public', as: 'public'
  post 'avatarchange', to: 'users#avatarchange', as: 'avatarchange'
  match '/faq', to: 'users#faq'
  post 'search', to: 'users#search', as: 'search'
  
  resources :posts, except: [:show]
  get 'drafts', to: 'posts#drafts', as: 'drafts'
  get 'posts/:id/publish', to: 'posts#publish', as: 'publish'
  post 'sms_post', to: 'posts#sms_post', as: 'sms_post'
  get 'preview/:id', to: 'posts#preview', as: 'preview'
  
  resources :activs, only: [:index]
  
  get 'followers', to: 'followings#followers', as: 'followers'
  get 'following', to: 'followings#following', as: 'following'
  post 'follow',   to: 'followings#create',    as: 'follow'
  post 'unfollow', to: 'followings#destroy',   as: 'unfollow'
  
  get  'likes',  to: 'likes#index',   as: 'likes'
  post 'like',   to: 'likes#create',  as: 'like'
  post 'unlike', to: 'likes#destroy', as: 'unlike'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)
#  email                  :string(255)
#  blog_name              :string(255)
#  password_digest        :string(255)
#  session_token          :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string(255)
#  uid                    :string(255)
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  phonenumber            :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :username, :email, :blog_name, :password, :provider, :uid, :avatar, :phonenumber
  attr_reader :password
    
  before_validation :ensure_session_token
  validates :username, :email, :blog_name, presence: true
  validates :username, :email, :blog_name, length: 4..40
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates :password, length: 4..15, allow_nil: true
  
  has_many :posts, dependent: :destroy
  has_many :sent_activs, class_name: "Activ", foreign_key: "sent_user_id", dependent: :destroy
  has_many :got_activs,  class_name: "Activ", foreign_key: "got_user_id",  dependent: :destroy
  has_many :followers, class_name: "Following", foreign_key: "followed_id", dependent: :destroy
  has_many :followers_users, through: :followers, source: :follower
  has_many :following, class_name: "Following", foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :following, source: :followed
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  # PAPERCLIP
  has_attached_file :avatar, styles: {small: "100x100>"}, default_url: "/assets/avatar_64_default1.png"
  validates_attachment_content_type :avatar, :content_type => %w[image/jpeg image/jpg image/png]
  validates_attachment :avatar, allow_nil: true, :size => { :in => 0..1000.kilobytes }
  
  def self.most_liked(except)
    User.find_by_sql(
    "SELECT users.*, COUNT(likes.id) AS count
    FROM users
    JOIN posts ON users.id = posts.user_id
    JOIN likes ON posts.id = likes.post_id
    WHERE users.id NOT IN (#{except.join(",")})
    GROUP BY users.id
    ORDER BY count DESC
    LIMIT 3")
  end
  
  def self.find_or_create_by_auth(auth, current_user)
    user = User.find_by_uid(auth['uid'])
    if user
      if current_user && user != current_user
        return false
      else
        return user
      end
    end
      
    user = User.find_by_email(auth['info']['email'])
    
    if user
      user.update_attributes({provider: auth['provider'], uid: auth['uid']})
      return user
    end
    
    if current_user
      current_user.update_attributes({provider: auth['provider'], uid: auth['uid']})
      return current_user
    end

    user = User.create!(
      username: auth['info']['nickname'],
      email: auth['info']['email'],
      blog_name: auth['info']['name'],
      password: auth['uid'],
      provider: auth['provider'],
      uid: auth['uid'])
    return user
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil unless user
    BCrypt::Password.new(user.password_digest).is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    return self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
  
  def send_password_reset
    self.password_reset_token = SecureRandom.urlsafe_base64(16)
    self.password_reset_sent_at = Time.zone.now
    self.save!
    UserMailer.password_reset(self).deliver
  end
  
  def src_small
    avatar? ? avatar.url : "No"
  end
end

app/models/users.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  blog_name       :string(255)
#  password_digest :string(255)
#  session_token   :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Users < ActiveRecord::Base
  attr_accessible :username, :email, :blog_name, :password
  attr_reader :password
  
  before_validation :ensure_session_token
  validates :username, :email, :blog_name, presence: true
  validates :username, :email, :blog_name, length: 4..30
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :username, :email, uniqueness: true
  
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil unless user
    BCrypt::Password.new(user.password_digest).is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    return self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, except: [:new, :create]
  before_filter :get_menu_stats, except: [:new, :create, :search]
  layout "auth", only: [:new, :create]
  
  def new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      signin(@user)
      flash[:main] = "You have been successfully registered"
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.messages
      render :new
    end 
  end
  
  def show
    users = [].push(current_user).concat(current_user.following_users)
    @posts = Post.where("draft=? AND user_id IN (?)", false, users)
                 .includes(:user)
                 .order("created_at DESC")
                        
    @liked_posts = current_user.liked_posts.pluck(:id)
  end
  
  def edit
  end
  
  def update
    @referer = params[:back]
    send_sms = params[:user][:phonenumber] != current_user.phonenumber
    
    if (params[:user][:password].empty? || params[:user][:cpassword].empty?)
      params[:user].delete(:password)
      params[:user].delete(:cpassword)
    else
      if params[:user][:password] != params[:user][:cpassword]
        flash.now[:errors] = {"Passwords don't match" => ""}
        render :edit
        return
      end
    end
    
    params[:user].delete(:cpassword)
    params[:user][:phonenumber] = nil if params[:user][:phonenumber].scan(/\A\+\d{11}\z/).first.nil?
    
    if current_user.update_attributes(params[:user])
      
      # PHONE NUMBER CHECK
      if (send_sms && current_user.phonenumber)
        to = current_user.phonenumber
        body = 'To post directly from your cellphone, send text messages to this number.'
        send_sms(to, body)
      end
      
      flash[:main] = "Your account has been updated"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    else
      flash.now[:errors] = current_user.errors.messages
      render :edit
    end
  end
  
  def findblogs
    except = [current_user.id].concat(current_user.following_users)
    @blogs = User.where("id NOT IN (?)", except).order("RANDOM()").limit(20)
  end
  
  def public
    user = User.find(params[:id])
    @posts = Post.where("draft=? AND user_id=?", false, user)
                 .includes(:user)
                 .order("created_at DESC")
    
    @liked_posts = current_user.liked_posts.pluck(:id)
  end
  
  def destroy
    if current_user.id == 1
      flash[:main] = "Can't delete demo account"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    end
    
    if current_user.destroy
      redirect_to root_url
    else
      flash[:main] = "Error in deleting your account"
      (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
    end
  end
  
  def avatarchange
    current_user.avatar = params[:avatar]
    current_user.save
    (params[:back].nil?) ? (redirect_to root_url) : (redirect_to params[:back])
  end
  
  def faq
  end
  
  def search
    # ONLY FOR AJAX
    if request.xhr?
      followings = [].concat(current_user.following.pluck(:followed_id))
      user = User.find_by_sql("SELECT * FROM users
                               WHERE id != #{current_user.id}
                               AND id NOT IN (#{followings.join(',')})
                               AND users.email LIKE '%#{params[:email]}%'
                               LIMIT 5")
      user = [].concat(user)
      unless user.empty?
        render json: user
      else
        render text: "Not Found"
      end
    end
  end
end

app/views/users/edit.html.erb
<div id="white_pane">
	<div class="title_and_controls group">
		<div class="profile_settings_title">Profile Settings</div>
		
		<!-- DELETE ACCOUNT BUTTON -->
		<% unless current_user.id == 1 %>
			<form action="<%= user_url(current_user.id) %>" method="post">
				<input type="hidden" name="_method" value="delete">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input type="hidden" name="back" value="<%= request.url %>">
				<input class="button_delete_account" type="submit" value="Delete Account">
			</form>
		<% end %>
	</div>
	
	<!-- AVATAR UPLOAD -->
	<div class="avatar_section">
		<div class="word_divider">Avatar</div>
		<%= image_tag current_user.avatar.url(:small), class: "settings_page_avatar" %>
		<form action="<%= avatarchange_url %>" method="post" enctype="multipart/form-data">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="back" value="<%= request.url %>">
			<div class="new_choose_file">Choose File</div><input id="old_choose_file" type="file" name="avatar">
			<input class="file_upload_button" type="submit" value="Upload">
		</form>
		
		<!-- FACEBOOK BUTTON -->
		<% if current_user.uid %>
			<div class="group">
				<div class="float_left">
					<a class="facebook_disconnect relative" href="<%= facebook_destroy_url %>">
						<div class="facebook_logo"></div>
						Disconnect
					</a>
				</div>
			</div>
		<% else %>
			<div class="group">
				<div class="float_left">
					<a class="facebook_connect relative" href="/auth/facebook">
						<div class="facebook_logo"></div>
						Connect
					</a>
				</div>
			</div>		
		<% end %>
	</div>

	<form class="profile_settings" action="<%= user_url(current_user.id) %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="_method" value="put">
		<input type="hidden" name="back" value="<%= @referer ||= request.url %>">
			
		<div class="word_divider">Basic Info</div>
		<input type="text" name="user[username]" value="<%= current_user.username %>" placeholder="Username">
		<input type="text" name="user[email]" value="<%= current_user.email %>" placeholder="Email">
		<input type="text" name="user[blog_name]" value="<%= current_user.blog_name %>" placeholder="Blog Name">
		
		<div class="word_divider">Cell Phone</div>
		<input type="tel" name="user[phonenumber]" value="<%= current_user.phonenumber %>" placeholder="Your cell phone number to post from ( e.x.: +15554447777 )">
		
		<div class="word_divider">Password Reset</div>
		<input type="password" name="user[password]" placeholder="New Password">
		<input type="password" name="user[cpassword]" placeholder="Confirm Password">

		<% if flash.now[:errors] %>
			<% history = [] %>
			<% flash.now[:errors].each do |key, val| %>
				<% unless history.include?(key) %>
					<div class="profile_settings_error" style="float: none"><%= key.capitalize %> <%= val.first %></div>
					<% break %>
					<% history << key %>
				<% end %>
			<% end %>
		<% end %>

		<div style="margin: 30px 0">
			<div class="float_left">
				<input type="submit" value="Save">
			</div>
			<div>
				<a class="float_right new_post_cancel" href="<%= @referer ||= request.referer %>">Cancel</a>
			</div>
		</div>
		<div style="clear:left"></div>
	</form>

</div>

<script>
$(document).ready(function(){
	$('.new_choose_file').bind("click" , function () {
	  $('#old_choose_file').click();
  });
	
	$('.file_upload_button').on("click", function() {
		event.preventDefault();
	});
	
	$('#old_choose_file').change(function(){
		if ( $(this).val() == "" ) {
			$('.file_upload_button').removeClass('activ_upload');
			$('.file_upload_button').on("click", function() {
				event.preventDefault();
			});
		} else {
			$('.file_upload_button').addClass('activ_upload');
			$('.file_upload_button').off();
		}
	})
});
</script>

app/views/users/faq.html.erb
<div id="white_pane">
	<div class="top_page_name">Info</div>
	
	<div class="faq_divider">About</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">Website name:</div>
		<div class="float_left faq_line_height">Tumblr-Clone</div>
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">Original Website:</div>
		<div class="float_left faq_line_height"><a href="http://www.tumblr.com">www.tumblr.com</a></div>
	</div>
	
	<div class="faq_divider">Contact</div>
	<div class="float_right">
		<img src="/assets/avatar_64_me.png" style="margin-right:20px;border-radius:8px">
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">Developer:</div>
		<div class="float_left faq_line_height">Raman Sycheuski</div>
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">Email:</div>
		<div class="float_left faq_line_height">raman.sycheuski@gmail.com</div>
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">Personal Website:</div>
		<div class="float_left faq_line_height">
			<a href="http://www.ramansycheuski.com/" target="blank">www.ramansycheuski.com</a>
		</div>
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">LinkedIn:</div>
		<div class="float_left faq_line_height">
			<a href="http://www.linkedin.com/in/ramansycheuski" target="blank">
				<img class="inline_logo" src="/assets/logo-linkedin.png">
			</a>
		</div>
	</div>
	<div class="group">
		<div class="float_left stronger faq_line_height">GitHub:</div>
		<a href="https://github.com/Roma198808" target="blank">
			<img class="inline_logo" src="/assets/logo-github.png">
		</a>
	</div>
</div>

app/views/users/findblogs.html.erb
<div id="white_pane">
	
	<div>
		<form action="<%= search_url %>" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="text" name="email" class="search_input" placeholder="Find a user by email" autocomplete="off">
		</form>
		<div id="search_results"></div>
	</div>
	
	<div class="title_and_controls">
		<a class="button_generate" href="<%= findblogs_url %>">Generate random</a>
	</div>

	<% if @blogs %>
		<ul class="random_blogs_list">
			<% @blogs.each_with_index do |blog, i| %>
				<li class="following_list_items<%= " follower_list_darker_bg" if i%2 != 0 %>">
					
					<div class="float_left">
						<a href="<%= public_url(blog.id) %>">
							<%= image_tag blog.avatar.url(:small), class: "avatar_40 float_left" %>
						</a>
						
						<a href="<%= public_url(blog.id) %>">
							<div class="float_left" style="margin-left: 12px;">
								<div class="following_username fingblogs_username"><%= blog.username %></div>
								<div class="following_username">"<%= blog.blog_name %>"</div>
							</div>
						</a>
					</div>
					

					<div class="float_right">
						<form action="<%= follow_url %>" method="post" style="line-height: 40px" data-id="<%= blog.id %>" class="blue_follow_button">
							<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
							<input type="hidden" name="back" value="<%= request.url %>">
							<input type="hidden" name="follower_id" value="<%= blog.id %>">
							<input class="button_follow_blue_big" type="submit" value="Follow">
						</form>
					</div>

				</li>
			<% end %>
		</ul>
	<% end %>
</div>

<script>
	$( document ).ready(function() {
		
		// SEARCH BOX
		$('.search_input').keyup(function() {
	    var $val = $(this).val();
			if ($val) {
		    $.ajax({
		      url: '/search',
		      type: "POST",
		      data: 'email=' + $val,
		      success: function(data) {
						if (data && data != "Not Found") {
							$('#search_results').html('');
							$('#search_results').css({'margin-bottom':'50px','padding-left':'10px'});
							data.forEach(function (el) {
								$('#search_results').append('<a class="search_result_line" href="/users/' + el.id + '/public">' + el.email + '<form action="/follow" method="post" style="display:inline;"><input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"><input type="hidden" name="back" value="/findblogs"><input type="hidden" name="follower_id" value="' + el.id + '"><input class="button_follow_blue_big float_right" type="submit" value="Follow"></form></a>');
							})
						} else {
							$('#search_results').html('<div>Not Found</div>');
						}
		      }
		    });
			} else {
				$('#search_results').html('');
			}
		});
		
	});
</script>

app/views/users/new.html.erb
<div class="auth_bg">
	
		<div class="logo" style="margin-top: 120px"><img src="/assets/white-logo.png"></div>
		
		<form action="<%= signin_url %>" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="user[email]" value="user@example.com">
			<input type="hidden" name="user[password]" value="password">
			<input class="button_demo_login" type="submit" value="Demo Account">
		</form>
		
		<a href="/auth/facebook" class="omniauth_facebook">Sign In with Facebook</a>
	
		
		<div class="center">
						
			<div class="text">Follow the blogs you've been hearing about.<br>
			Share the things you love.</div>

			<form action="<%= users_url %>" method="post">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
				<input type="text" class="auth_input" name="user[email]"  placeholder="Email" value="<%= @user && @user.email %>"><br>
				<input type="password" class="auth_input" name="user[password]"  placeholder="Password" value="<%= @user && @user.password %>"><br>
				<input type="text" class="auth_input" name="user[username]"  placeholder="Username" value="<%= @user && @user.username %>"><br>
				<input type="text" class="auth_input" name="user[blog_name]"  placeholder="Blog name" value="<%= @user && @user.blog_name %>"><br>
	
				<% if flash.now[:errors] %>
					<% history = [] %>
					<% flash.now[:errors].each do |key, val| %>
						<% unless history.include?(key) %>
							<div class="auth_error"><%= key.capitalize %> <%= val.first %></div>
							<% break %>
							<% history << key %>
						<% end %>
					<% end %>
				<% end %>

				<input class="auth_input auth_action" type="submit" value="Sign up">
			</form>
			
			
	</div>
	
				<a class="auth_input bottom" href="<%= login_url %>">Sign in</a>
</div>

app/views/users/public.html.erb
<div class="relative"><div class="post_avatar_top"><div class="selector_left"></div></div></div>

<%= render 'posts/new_post_menu' %>

<%= render 'posts/post_items' %>

app/views/users/show.html.erb
<%= render 'posts/new_post_menu' %>

<%= render 'posts/post_items' %>